export const SHOW_ALL_WISHLIST = 'LIST_WISHLIST';
export const IS_IN_WISHLIST = 'IS_IN_WISHLIST';
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const DELETE_WISHLIST = 'DELETE_WISHLIST';
export const ERROR_WISHLIST = 'ERROR_WISHLIST';

export const SHOW_ALL_PRODUCT = 'SHOW_ALL_PRODUCT';
export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const SHOW_ALL_SELLER_PRODUCT = 'SHOW_ALL_SELLER_PRODUCT';
export const SELLER_ERROR = 'SELLER_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
