export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const GET_USER = 'GET_USER';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const UPDATE_USER = 'UPDATE_USER';
export const FAILED_UPDATE_USER = 'FAILED_UPDATE_USER';
export const REGISTER_SELLER = 'REGISTER_SELLER';
export const LOGOUT = 'LOGOUT';

export const SHOW_ALL_PRODUCT = 'SHOW_ALL_PRODUCT';
export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';

export const SHOW_ALL_SELLER_PRODUCT = 'SHOW_ALL_SELLER_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const SHOW_ALL_BID = 'SHOW_ALL_BID';
export const SHOW_BID = 'SHOW_BID';
export const SHOW_BUYER_BID = 'SHOW_BUYER_BID';
export const ADD_BID = 'ADD_BID';
export const UPDATE_BID = 'UPDATE_BID';
export const DELETE_BID = 'DELETE_BID';
export const ACCEPT_BID = 'ACCEPT_BID';
export const PAY_BID = 'PAY_BID';
export const GET_INVOICE = 'GET_INVOICE';

export const SHOW_ALL_WISHLIST = 'LIST_WISHLIST';
export const IS_IN_WISHLIST = 'IS_IN_WISHLIST';
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const DELETE_WISHLIST = 'DELETE_WISHLIST';

export const SHOW_ALL_NOTIF = 'SHOW_ALL_NOTIF';
export const UPDATE_NOTIF = 'UPDATE_NOTIF';
